export const MOCK_DESTINATIONS = [
  {
    xid: 'mock_paris',
    name: 'Paris',
    country: 'France',
    description:
      "Paris, the City of Light, is France's capital and a global hub of art, fashion, gastronomy, and culture. With iconic landmarks like the Eiffel Tower, the Louvre, and Notre-Dame Cathedral, Paris enchants millions of visitors each year with its unmatched elegance and romance.",
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&q=80',
    lat: 48.8566,
    lon: 2.3522,
    rating: 4.9,
    tags: ['culture', 'art', 'romance', 'food'],
  },
  {
    xid: 'mock_tokyo',
    name: 'Tokyo',
    country: 'Japan',
    description:
      "Tokyo, Japan's bustling capital, mixes ultramodern and traditional elements, from neon-lit skyscrapers and anime shops to historic temples and traditional tea houses. A world-class city that never sleeps, offering extraordinary cuisine, cutting-edge technology, and vibrant pop culture.",
    image: 'https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80',
    lat: 35.6762,
    lon: 139.6503,
    rating: 4.8,
    tags: ['technology', 'culture', 'food', 'urban'],
  },
  {
    xid: 'mock_nyc',
    name: 'New York City',
    country: 'United States',
    description:
      "New York City comprises 5 boroughs sitting where the Hudson River meets the Atlantic Ocean. At its core is Manhattan, a densely populated borough that's among the world's major commercial, financial, and cultural centers. Its iconic sites include skyscrapers such as the Empire State Building and sprawling Central Park.",
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&q=80',
    lat: 40.7128,
    lon: -74.006,
    rating: 4.7,
    tags: ['urban', 'culture', 'food', 'art'],
  },
  {
    xid: 'mock_bali',
    name: 'Bali',
    country: 'Indonesia',
    description:
      "Bali is a living postcard—an Indonesian paradise that feels like a fantasy. Aside from a cacophony of sound and color, there's an essence of peaceful harmony that is difficult to describe. From terraced rice fields and volcanic mountains to pristine beaches and coral reefs, Bali is a sensory overload in the best possible way.",
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&q=80',
    lat: -8.4095,
    lon: 115.1889,
    rating: 4.8,
    tags: ['beach', 'nature', 'culture', 'spiritual'],
  },
  {
    xid: 'mock_rome',
    name: 'Rome',
    country: 'Italy',
    description:
      "Rome, Italy's capital, is a sprawling, cosmopolitan city with nearly 3,000 years of globally influential art, architecture, and culture on display. Ancient ruins such as the Forum and the Colosseum evoke the power of the former Roman Empire. The Vatican City, headquarters of the Roman Catholic Church, features St. Peter's Basilica and the Vatican Museums.",
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=800&q=80',
    lat: 41.9028,
    lon: 12.4964,
    rating: 4.7,
    tags: ['history', 'art', 'food', 'architecture'],
  },
  {
    xid: 'mock_dubai',
    name: 'Dubai',
    country: 'UAE',
    description:
      "Dubai is a city and emirate in the United Arab Emirates known for luxury shopping, ultramodern architecture, and a lively nightlife scene. Burj Khalifa, an 830m-tall tower, dominates the skyscraper-filled skyline. At its foot, the Dubai Fountain system choreographs jets and lights to music. On the coast is Atlantis, The Palm, a resort with a waterpark and a major aquarium.",
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    lat: 25.2048,
    lon: 55.2708,
    rating: 4.6,
    tags: ['luxury', 'shopping', 'modern', 'desert'],
  },
  {
    xid: 'mock_delhi',
    name: 'New Delhi',
    country: 'India',
    description:
      "New Delhi, India's capital, is a sprawling metropolis that blends ancient history with modern India. From the majestic Red Fort and Qutub Minar to the bustling lanes of Chandni Chowk and the grandeur of India Gate, Delhi offers an unmatched journey through centuries of culture, cuisine, and civilization.",
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&q=80',
    lat: 28.6139,
    lon: 77.2090,
    rating: 4.6,
    tags: ['history', 'culture', 'food', 'heritage'],
  },
  {
    xid: 'mock_agra',
    name: 'Agra',
    country: 'India',
    description:
      "Agra is home to one of the Seven Wonders of the World — the Taj Mahal, a stunning white marble mausoleum built by Mughal emperor Shah Jahan. Beyond the Taj, Agra Fort and Fatehpur Sikri make this city an unmissable stop on any India itinerary.",
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&q=80',
    lat: 27.1767,
    lon: 78.0081,
    rating: 4.9,
    tags: ['history', 'heritage', 'architecture', 'iconic'],
  },
  {
    xid: 'mock_jaipur',
    name: 'Jaipur',
    country: 'India',
    description:
      "Jaipur, the Pink City of Rajasthan, is a royal city of palaces, forts, and vivid bazaars. Known for its stunning Amber Fort, the ornate Hawa Mahal, and City Palace, Jaipur is a feast for the eyes and one of India's most visited destinations.",
    image: 'https://images.unsplash.com/photo-1477587458883-47145ed94245?w=800&q=80',
    lat: 26.9124,
    lon: 75.7873,
    rating: 4.7,
    tags: ['culture', 'history', 'architecture', 'shopping'],
  },
  {
    xid: 'mock_kerala',
    name: 'Kerala',
    country: 'India',
    description:
      "Kerala, known as God's Own Country, is India's lush tropical paradise. Famous for its serene backwaters, houseboat cruises, pristine beaches, and misty hill stations like Munnar, Kerala also boasts Ayurvedic wellness retreats and rich cultural traditions.",
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&q=80',
    lat: 10.8505,
    lon: 76.2711,
    rating: 4.8,
    tags: ['nature', 'beach', 'spiritual', 'wellness'],
  },
  {
    xid: 'mock_mumbai',
    name: 'Mumbai',
    country: 'India',
    description:
      "Mumbai, India's financial capital and city of dreams, is a dynamic metropolis where colonial-era architecture meets a buzzing modern skyline. Home to Bollywood, the iconic Gateway of India, Marine Drive, and a vibrant street food scene.",
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&q=80',
    lat: 19.0760,
    lon: 72.8777,
    rating: 4.5,
    tags: ['urban', 'food', 'culture', 'modern'],
  },
  {
    xid: 'mock_varanasi',
    name: 'Varanasi',
    country: 'India',
    description:
      "Varanasi, one of the world's oldest living cities and the spiritual capital of India, sits on the banks of the sacred Ganges River. Pilgrims come to bathe in the holy ghats and witness the mesmerizing Ganga Aarti ceremony at dusk.",
    image: 'https://images.unsplash.com/photo-1561361058-c24e01fc61bc?w=800&q=80',
    lat: 25.3176,
    lon: 82.9739,
    rating: 4.7,
    tags: ['spiritual', 'culture', 'history', 'heritage'],
  },
  {
    xid: 'mock_goa',
    name: 'Goa',
    country: 'India',
    description:
      "Goa, India's smallest state, is famous for its stunning beaches, Portuguese colonial heritage, vibrant nightlife, and laid-back atmosphere. From Baga and Calangute in the north to tranquil Palolem in the south, Goa caters to every traveler.",
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&q=80',
    lat: 15.2993,
    lon: 74.1240,
    rating: 4.6,
    tags: ['beach', 'nature', 'culture', 'food'],
  },
];


export const MOCK_ATTRACTIONS = {
  mock_paris: [
    { name: 'Eiffel Tower', kinds: 'historic,towers', preview: { title: 'Eiffel Tower' } },
    { name: 'The Louvre', kinds: 'museums,art', preview: { title: 'The Louvre' } },
    { name: 'Notre-Dame Cathedral', kinds: 'churches,historic', preview: { title: 'Notre-Dame' } },
    { name: 'Arc de Triomphe', kinds: 'historic,monuments', preview: { title: 'Arc de Triomphe' } },
    { name: 'Musée d\'Orsay', kinds: 'museums,art', preview: { title: 'Musée d\'Orsay' } },
    { name: 'Sacré-Cœur Basilica', kinds: 'churches,panoramas', preview: { title: 'Sacré-Cœur' } },
  ],
  mock_tokyo: [
    { name: 'Senso-ji Temple', kinds: 'temples,historic', preview: { title: 'Senso-ji' } },
    { name: 'Tokyo Skytree', kinds: 'towers,panoramas', preview: { title: 'Tokyo Skytree' } },
    { name: 'Shibuya Crossing', kinds: 'urban,famous_places', preview: { title: 'Shibuya Crossing' } },
    { name: 'teamLab Planets', kinds: 'museums,art', preview: { title: 'teamLab' } },
    { name: 'Meiji Shrine', kinds: 'shrines,nature', preview: { title: 'Meiji Shrine' } },
    { name: 'Tsukiji Fish Market', kinds: 'markets,food', preview: { title: 'Tsukiji Market' } },
  ],
  mock_nyc: [
    { name: 'Statue of Liberty', kinds: 'historic,monuments', preview: { title: 'Statue of Liberty' } },
    { name: 'Central Park', kinds: 'parks,nature', preview: { title: 'Central Park' } },
    { name: 'Empire State Building', kinds: 'towers,panoramas', preview: { title: 'Empire State Building' } },
    { name: 'Metropolitan Museum', kinds: 'museums,art', preview: { title: 'The Met' } },
    { name: 'Brooklyn Bridge', kinds: 'historic,architecture', preview: { title: 'Brooklyn Bridge' } },
    { name: 'Times Square', kinds: 'urban,famous_places', preview: { title: 'Times Square' } },
  ],
  mock_bali: [
    { name: 'Tanah Lot Temple', kinds: 'temples,historic', preview: { title: 'Tanah Lot' } },
    { name: 'Tegallalang Rice Terraces', kinds: 'nature,panoramas', preview: { title: 'Tegallalang' } },
    { name: 'Ubud Monkey Forest', kinds: 'nature,parks', preview: { title: 'Monkey Forest' } },
    { name: 'Kuta Beach', kinds: 'beaches,nature', preview: { title: 'Kuta Beach' } },
    { name: 'Mount Batur', kinds: 'nature,volcanoes', preview: { title: 'Mount Batur' } },
    { name: 'Tirta Empul Temple', kinds: 'temples,spiritual', preview: { title: 'Tirta Empul' } },
  ],
  mock_rome: [
    { name: 'Colosseum', kinds: 'historic,amphitheaters', preview: { title: 'Colosseum' } },
    { name: 'Vatican Museums', kinds: 'museums,art', preview: { title: 'Vatican Museums' } },
    { name: 'Trevi Fountain', kinds: 'historic,fountains', preview: { title: 'Trevi Fountain' } },
    { name: 'Roman Forum', kinds: 'historic,ruins', preview: { title: 'Roman Forum' } },
    { name: 'Pantheon', kinds: 'historic,architecture', preview: { title: 'Pantheon' } },
    { name: 'Borghese Gallery', kinds: 'museums,art', preview: { title: 'Borghese Gallery' } },
  ],
  mock_dubai: [
    { name: 'Burj Khalifa', kinds: 'towers,panoramas', preview: { title: 'Burj Khalifa' } },
    { name: 'Dubai Mall', kinds: 'shopping,urban', preview: { title: 'Dubai Mall' } },
    { name: 'Palm Jumeirah', kinds: 'architecture,famous_places', preview: { title: 'Palm Jumeirah' } },
    { name: 'Desert Safari', kinds: 'nature,adventure', preview: { title: 'Desert Safari' } },
    { name: 'Dubai Frame', kinds: 'architecture,panoramas', preview: { title: 'Dubai Frame' } },
    { name: 'Gold Souk', kinds: 'markets,shopping', preview: { title: 'Gold Souk' } },
  ],
  mock_delhi: [
    { name: 'Red Fort', kinds: 'historic,architecture', preview: { title: 'Red Fort' } },
    { name: 'Qutub Minar', kinds: 'historic,monuments', preview: { title: 'Qutub Minar' } },
    { name: 'India Gate', kinds: 'historic,monuments', preview: { title: 'India Gate' } },
    { name: "Humayun's Tomb", kinds: 'historic,architecture', preview: { title: "Humayun's Tomb" } },
    { name: 'Chandni Chowk', kinds: 'markets,food', preview: { title: 'Chandni Chowk' } },
    { name: 'Lotus Temple', kinds: 'temples,architecture', preview: { title: 'Lotus Temple' } },
  ],
  mock_agra: [
    { name: 'Taj Mahal', kinds: 'historic,architecture', preview: { title: 'Taj Mahal' } },
    { name: 'Agra Fort', kinds: 'historic,architecture', preview: { title: 'Agra Fort' } },
    { name: 'Fatehpur Sikri', kinds: 'historic,ruins', preview: { title: 'Fatehpur Sikri' } },
    { name: 'Mehtab Bagh', kinds: 'nature,parks', preview: { title: 'Mehtab Bagh' } },
    { name: "Akbar's Tomb", kinds: 'historic,monuments', preview: { title: "Akbar's Tomb" } },
    { name: 'Kinari Bazaar', kinds: 'markets,shopping', preview: { title: 'Kinari Bazaar' } },
  ],
  mock_jaipur: [
    { name: 'Amber Fort', kinds: 'historic,architecture', preview: { title: 'Amber Fort' } },
    { name: 'Hawa Mahal', kinds: 'historic,architecture', preview: { title: 'Hawa Mahal' } },
    { name: 'City Palace', kinds: 'historic,museums', preview: { title: 'City Palace' } },
    { name: 'Jantar Mantar', kinds: 'historic,monuments', preview: { title: 'Jantar Mantar' } },
    { name: 'Nahargarh Fort', kinds: 'historic,panoramas', preview: { title: 'Nahargarh Fort' } },
    { name: 'Johari Bazaar', kinds: 'markets,shopping', preview: { title: 'Johari Bazaar' } },
  ],
  mock_kerala: [
    { name: 'Alleppey Backwaters', kinds: 'nature,panoramas', preview: { title: 'Alleppey Backwaters' } },
    { name: 'Munnar Tea Gardens', kinds: 'nature,panoramas', preview: { title: 'Munnar' } },
    { name: 'Periyar Wildlife Sanctuary', kinds: 'nature,parks', preview: { title: 'Periyar' } },
    { name: 'Varkala Beach', kinds: 'beaches,nature', preview: { title: 'Varkala Beach' } },
    { name: 'Padmanabhaswamy Temple', kinds: 'temples,historic', preview: { title: 'Padmanabhaswamy' } },
    { name: 'Kathakali Show', kinds: 'art,culture', preview: { title: 'Kathakali' } },
  ],
  mock_mumbai: [
    { name: 'Gateway of India', kinds: 'historic,monuments', preview: { title: 'Gateway of India' } },
    { name: 'Marine Drive', kinds: 'urban,famous_places', preview: { title: 'Marine Drive' } },
    { name: 'Elephanta Caves', kinds: 'historic,temples', preview: { title: 'Elephanta Caves' } },
    { name: 'Chhatrapati Shivaji Museum', kinds: 'museums,art', preview: { title: 'CSMVS Museum' } },
    { name: 'Juhu Beach', kinds: 'beaches,food', preview: { title: 'Juhu Beach' } },
    { name: 'Dharavi', kinds: 'urban,culture', preview: { title: 'Dharavi' } },
  ],
  mock_varanasi: [
    { name: 'Dashashwamedh Ghat', kinds: 'temples,spiritual', preview: { title: 'Dashashwamedh Ghat' } },
    { name: 'Ganga Aarti Ceremony', kinds: 'temples,spiritual', preview: { title: 'Ganga Aarti' } },
    { name: 'Kashi Vishwanath Temple', kinds: 'temples,historic', preview: { title: 'Kashi Vishwanath' } },
    { name: 'Sarnath', kinds: 'historic,temples', preview: { title: 'Sarnath' } },
    { name: 'Manikarnika Ghat', kinds: 'temples,spiritual', preview: { title: 'Manikarnika Ghat' } },
    { name: 'Ramnagar Fort', kinds: 'historic,architecture', preview: { title: 'Ramnagar Fort' } },
  ],
  mock_goa: [
    { name: 'Baga Beach', kinds: 'beaches,nature', preview: { title: 'Baga Beach' } },
    { name: 'Basilica of Bom Jesus', kinds: 'churches,historic', preview: { title: 'Bom Jesus Basilica' } },
    { name: 'Dudhsagar Falls', kinds: 'nature,panoramas', preview: { title: 'Dudhsagar Falls' } },
    { name: 'Fort Aguada', kinds: 'historic,architecture', preview: { title: 'Fort Aguada' } },
    { name: 'Palolem Beach', kinds: 'beaches,nature', preview: { title: 'Palolem Beach' } },
    { name: 'Anjuna Flea Market', kinds: 'markets,shopping', preview: { title: 'Anjuna Market' } },
  ],
};

export const MOCK_WEATHER = {
  mock_paris:    { temp: 18, feels_like: 16, description: 'Partly Cloudy',  humidity: 72, wind: 12, code: 801 },
  mock_tokyo:    { temp: 22, feels_like: 21, description: 'Clear Sky',       humidity: 65, wind: 8,  code: 800 },
  mock_nyc:      { temp: 15, feels_like: 13, description: 'Light Rain',      humidity: 80, wind: 18, code: 500 },
  mock_bali:     { temp: 30, feels_like: 34, description: 'Tropical Shower', humidity: 85, wind: 10, code: 521 },
  mock_rome:     { temp: 25, feels_like: 24, description: 'Sunny',           humidity: 55, wind: 7,  code: 800 },
  mock_dubai:    { temp: 38, feels_like: 42, description: 'Hot & Clear',     humidity: 40, wind: 15, code: 800 },
  mock_delhi:    { temp: 34, feels_like: 38, description: 'Hot & Hazy',      humidity: 55, wind: 10, code: 721 },
  mock_agra:     { temp: 33, feels_like: 37, description: 'Sunny & Hot',     humidity: 50, wind: 9,  code: 800 },
  mock_jaipur:   { temp: 36, feels_like: 40, description: 'Dry & Sunny',     humidity: 35, wind: 14, code: 800 },
  mock_kerala:   { temp: 28, feels_like: 32, description: 'Humid & Warm',    humidity: 88, wind: 12, code: 801 },
  mock_mumbai:   { temp: 31, feels_like: 36, description: 'Warm & Humid',    humidity: 80, wind: 16, code: 802 },
  mock_varanasi: { temp: 32, feels_like: 35, description: 'Clear & Hot',     humidity: 58, wind: 8,  code: 800 },
  mock_goa:      { temp: 29, feels_like: 33, description: 'Warm & Breezy',   humidity: 78, wind: 20, code: 801 },
};